"""
Module to hold common text messages and strings.
"""

MAX_TIME = "MAX_TIME"
ERROR = "ERROR"
NOOP = "NOOP"

# Commands
RELAY_ON_COMMAND = "ON"
RELAY_OFF_COMMAND = "OFF"
SHUTDOWN_COMMAND = "SHUTDOWN"
RESTART_COMMAND = "RESTART"
FULL_STATUS_COMMAND = "STATUS"
HELP_COMMAND = "HELP"
QUIT_COMMAND = "QUIT"
UPTIME_COMMAND = "UPTIME"
